---
--- Generated by Luanalysis
--- Created by zhl36.
--- DateTime: 2024-04-08 9:03
---

 --比较线程标识与锁中的标识是否一致
if (redis.call('get',KEYS[1]) == ARGV[1]) then
    -- 一致 释放锁
    return redis.call('del',KEYS[1])
end
-- 不一致 直接返回
return 0